### ISSUE TITLE
用css控制文字的换行问题

### ISSUE THREAD

**Issue by incuisting** [incuisting/blogs#30]
强制不换行
```css
div{
white-space:nowrap;
}
```
自动换行
```css
div{ 
word-wrap: break-word; 
word-break: normal; 
}
```
强制英文单词断行
```css
div{
word-break:break-all;
}
 ```
